--- #YAML:1.0
name:                Lingua-Concordance
version:             0.02
abstract:            Keyword-in-context (KWIC) search interface
license:             ~
author:              
    - Eric Lease Morgan
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Math::Round:                   0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
